modLoader="kotlinforforge"
loaderVersion="[1.15,)"
license="Creative Commons Attribution-NonCommercial-NoDerivatives 4.0"
issueTrackerURL="https://github.com/ManApart/endersorts/issues"

[[mods]]
    modId="endersort"
    version="1.0"
    displayName="Endersort"
	authors="ManApart"
    description='''
    Deposit items and have them sorted to nearby chests
    '''
    credits="Sort your items"

[[dependencies.endersort]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"